## 난수 생성 함수

random

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2, 2)   # 0 ~ 1 사이에 값 랜덤
print(a)

[[0.36377426 0.44541229]
 [0.17048902 0.10574289]]


In [ ]:
b = np.random.randn(2, 2) # 평균이 0, 분산이 1 : 표준 정규 분포
print(b)

[[ 0.08849669 -1.56478463]
 [-1.13246312 -1.00713343]]


In [ ]:
c = np.random.randint(0, 10, size=5) # 랜덤한 정수값 (최솟값, 최댓값, 크기)
print(c)

[9 1 1 8 9]


In [ ]:
c2 = np.random.randint(0, 10, size=(2,2)) # 행렬로 지정할 수도 있음
print(c2)

[[0 4]
 [2 0]]


In [ ]:
d = np.arange(10) # 0 ~ 9까지 값을 생성
np.random.shuffle(d) # d 값을 무작위로 섞어줌. 복사본 생성 x , 원본 값이 변한다.
print(d)

[4 0 9 7 2 6 1 8 5 3]


In [ ]:
choice = np.random.choice(d, 5) # d에서 중복을 허용하여 5번 뽑는다
print(choice)

[1 4 5 5 6]


In [ ]:
choice = np.random.choice(d, 5, replace=False) # 중복을 허용하지 않는다.
print(choice)

[7 9 8 1 4]


In [ ]:
choice = np.random.choice(d, 5, p=[0.1, 0, 0.3 , 0.2, 0.1, 0.1, 0.1, 0 ,0, 0.1]) # p값의 전체 합이 1이 되도록 해야한다.
print(choice)

[1 9 9 1 9]


In [ ]:
# permutation 순열
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[0 1 4 8 7 9 2 5 3 6]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3) # 표준 정규분포
print(a)

[-0.30316056  0.95891576  1.52629811]


# Pandas

- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리 (비어있는 값)
- 데이터 변환
---
- 시계열 데이터 처리 (시계열: 시간의 흐름에따라 쌓인 데이터)
- 데이터 시각화

## 1. Series(시리즈)

- 인덱스를 지정할 수 있음


### 인덱싱

In [52]:
import pandas as pd

In [54]:
s = pd.Series([1, 2, 3, 4])  # 리스트
print(s) # 인덱스와 값이 매핑됨

0    1
1    2
2    3
3    4
dtype: int64


In [55]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4}) # 딕셔너리
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [57]:
s3 = pd.Series(5, index=[0, 1, 2]) # 스칼라
print(s3)

0    5
1    5
2    5
dtype: int64


In [59]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index) # 활용
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [61]:
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


### 슬라이싱

In [62]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [63]:
series[0]

1

In [65]:
series[0:4] # series[:-1]과 같음

0    1
1    2
2    3
3    4
dtype: int64

In [68]:
series[::-1] # 뒤에서부터 출력

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [69]:
print(series) # 원본은 바뀌지 않음

0    1
1    2
2    3
3    4
4    5
dtype: int64


#### Boolean indexing

In [74]:
print(series > 2)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [75]:
# 원하는 출력값 시리즈로 받기

print(series[series > 2]) # a[a조건]

2    3
3    4
4    5
dtype: int64


In [77]:
# 5보다 작은 시리즈 만들기

print(series[series < 5])

0    1
1    2
2    3
3    4
dtype: int64


### Series 산술 연산

In [78]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

In [83]:
print(series + 100)
print(series - 100) # 원본은 그대로

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64


In [88]:
# 곱하기: *
print(series * 100)

# 제곱: **
print(series ** 2)

# 나누기: /
print(series / 2)

# 나머지: %
print(series % 2)

# 몫: //
print(series // 2)

0    100
1    200
2    300
3    400
4    500
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64
0    1
1    0
2    1
3    0
4    1
dtype: int64
0    0
1    1
2    1
3    2
4    2
dtype: int64


## Series 객체에 접근

- keys :index를 가리킨다
- values

In [90]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

In [95]:
print(series.keys) # keys는 인덱스 자체의 값이 아님

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>


In [92]:
print(series.values)

[1 2 3 4 5]


In [101]:
print(series.keys())
print(series.index)
print(series.values)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [93]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
print(s2.keys)

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>


In [94]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [97]:
# items

print(s2.items()) # zip: 순회가능하고 쌍으로 이루어져있다

In [99]:
for index, value in s2.items():
  print(f'인데스: {index}, 데이터: {value}')

인데스: a, 데이터: 1
인데스: b, 데이터: 2
인데스: c, 데이터: 3
인데스: d, 데이터: 4


In [103]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

In [104]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [105]:
print(s.loc['b']) # loc:행에 접근
print(s.loc['b':'d']) # b ~ d 의 데이터 추출

20
b    20
c    30
d    40
dtype: int64


In [106]:
print(s.iloc[1]) # iloc: (행에 기반한)열에 접근

20


In [107]:
print(s.iloc[1:3])

b    20
c    30
dtype: int64


In [108]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [113]:
print(s.at['a']) # at은 loc과 비슷, 하나의 값만 가져올 때

10


In [110]:
print(s.iat[0])

10


In [116]:
print(s.get('e')) # 없는 값에 대한 처리 방법: error가 나지 않고 없다는 것을 알려줌
print(s.get('e', default=-1)) # 값이 없을 때 -1을 반환함

None
-1


## 결측값 (NaN, None)

- isna()
- isnull()

NaN(Not a Number) -> float

None -> none

In [121]:
data = [1, 2, 3, None]
s = pd.Series(data)
print(s.isna())
print(s.isnull())

0    False
1    False
2    False
3     True
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool


In [122]:
print(s.isna().sum()) # True 값의 합(True는 비어있는 값, 1) -> 비어있는 것의 갯수
print(s.isnull().sum()) # True 값의 합(True는 비어있는 값, 1) -> 비어있는 것의 갯수

1
1


In [123]:
print(s.notnull().sum()) # 비어있지 않은 것의 갯수를 셈

3


결측치 제거

In [124]:
s.dropna() # 비어있는 값 빼기

0    1.0
1    2.0
2    3.0
dtype: float64

결측치를 0으로 치환

In [129]:
s.fillna(0) # 결측치를 ()괄호 안에 있는 값으로 치환

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

## seires 함수

In [131]:
s = pd.Series([1, 3, 5, 7, 9])

In [132]:
s.count() # 원소의 수

5

In [133]:
s.min() # 최솟값

1

In [134]:
s.max() # 최댓값

9

In [135]:
print(s.mean()) # 평균
print(s.median()) # 중앙값
print(s.std()) # 표준편차
print(s.var()) # 분산

5.0
5.0
3.1622776601683795
10.0


In [136]:
s.describe() # 기초 통계 내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64