# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학 연산
- 배열 -> 행렬 (선형대수)
- 선형대수 , 푸리에 변환 -> 수학 함수

In [1]:
import numpy as np # numpy를 np이름으로 사용할 것이다

In [15]:
# 하나의 숫자값: 스칼라

s = np.array(1)
print(s)

1


In [2]:
# 1차원: 벡터
a = np.array([1, 2, 3, 4]) # 1차원 배열 생성

In [3]:
print(a) # 리스트와 달리 ,로 구분되지 않음. 1차원 배열

[1 2 3 4]


In [4]:
l = [1, 2, 3, 4]
print(l)

[1, 2, 3, 4]


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.ndim) # 배열의 차원

1


In [7]:
print(a.dtype) # 배열의 데이터 타입

int64


In [8]:
print(a.itemsize) # 각 요소의 바이트 단위 크기

8


In [11]:
# 2차원: 행렬(Matrix)
b = np.array([[1, 2], [2, 4]])  # 2차원은 2개의 꺽새

print(b)

[[1 2]
 [2 4]]


In [12]:
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

[[1 2]
 [2 4]]
2
int64
8
32


In [14]:
# 3차원: 텐서(Tensor)

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
8
64


In [17]:
# for문을 이용해서 배열 생성

f = np.array([i for i in range(0,10,2)]) # (start,end,step)
print(f)

[0 2 4 6 8]


In [18]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## 데이터 타입

1. 숫자형

2. 문자형

3. 논리형

### 숫자형

- 부호가 있는 정수 (Signed integer)
- 부호가 없는 정수 (Unsigned integer)
- 실수 (floating point)
- 복소수 (complex) 

In [19]:
# int (8bit, 16bit, 32bit, 64bit)

data = [1.1, 2, 3]

i = np.array(data, dtype = np.int32)
print(i)

[1 2 3]


In [20]:
print(i.dtype)

int32


In [24]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32) # -1이 uint32의 범위를 넘어서서 이상한 결과가 나옴
print(ui)

[4294967295          2          3]


In [25]:
f = np.array(data, dtype=np.float64)

print(f)

[1.1 2.  3. ]


In [27]:
c = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)

In [28]:
print(c.real) # 실수
print(c.imag) # 허수

[1. 3. 5.]
[2. 4. 6.]


### 문자형

- string_
- unicod_

In [29]:
data = [1, 2, 3]

s = np.string_(data)
print(s)

b'\x01\x02\x03'


In [30]:
print(s.dtype) # s3: string 3

|S3


In [34]:
data3 = [1, 2, 3, 4, 5]

# string_
s2 = np.string_(data3) # s2 = np.array(data3, dtype='S') 와 같은 표현

# print, 그 자체, 데이터 타입
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [41]:
u = np.array(data3, dtype='U') # unicode

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [37]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype='U')
print(u2.dtype)


<U2


### 논리형 (boolean)

- True(1), False(0)
- 비트 연산 사용


In [38]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [40]:
and_ = np.logical_and(l1, l2)
print(and_)

[False False False]


## 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰준다
- 예시) 이미지 데이터 -> uint 형으로 불러옴 -> 분석할때는 float형


In [42]:
data = [1.1, 2, 3]

a = np.float64(data) # np.데이터타입
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [45]:
a = a.astype(np.int64)

print(a)
print(a.dtype)

[1 2 3]
int64


In [47]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [50]:
b = b - 1 # uint형이던 b를 int형으로 자동 변환
print(b)

-3


In [55]:
c = np.uint16(-1) # uint16 (0 ~ 65535)
print(c)

65535


## 산술연산

In [68]:
import time

data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

start_time = time.time()

sum = 0
for i in range(len(data)): # range(2)
  for j in range(len(data[0])): #range(3)
     sum += data[i][j]
     print(i,j)

print(sum)


0 0
0 1
0 2
1 0
1 1
1 2
21


In [60]:
data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

print(len(data))
print(len(data2))
print(len(data[0]))

2
2
3


In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 덧셈
sum = a + b
print(sum)

# 뺄셈
min = a - b
print(min)
# 곱셈
mul = a * b
print(mul)
# 나눗셈
div = a / b
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# 지수함수
aa = np.exp(a) # e^a
print(aa)

In [72]:
# 자연로그
bb = np.log(b)
print(bb)

[1.38629436 1.60943791 1.79175947]


In [73]:
# 밑이 n인 로그
cc = np.log2(b) # 밑이 2인 로그
print(cc)

[2.         2.32192809 2.5849625 ]


In [74]:
# 삼각함수

d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)

cos_ = np.cos(d)

tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 배열의 연결과 분할

In [75]:
print('a' + 'b')

ab


In [76]:
x = [1, 2, 3]
y = [4, 5, 6]

In [78]:
concat = np.concatenate([x,y])
print(concat)

[1 2 3 4 5 6]


In [85]:
x2 = [[1, 2], [3, 4]] # 2 x 2
y2 = [[4, 5], [6, 7]] # 2 x 2

concat2 = np.concatenate([x2,y2], axis=1) # 열 방향
concat3 = np.concatenate([x2,y2], axis=0) # 행 방향
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [88]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [90]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
x2 = [[1, 2], [3, 4]] # 2 x 2
y2 = [[4, 5], [6, 7]] # 2 x 2

# hstack - 수평

h = np.hstack([x2, y2]) # 수평 열 방향
print(h)


[[1 2 4 5]
 [3 4 6 7]]


In [93]:
# vstack - 수직(vertical)

v = np.vstack([x2,y2]) # 수직 행 방향
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [95]:
# 분할
x2 = np.array([[1, 2], [3, 4], [5, 6]])

# hsplit
h2 = np.hsplit(x2, 2)
print(h2)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [99]:
# vsplit
x2 = np.array([[1, 2], [3, 4], [5, 6]])

v2 = np.vsplit(x2, 3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


## 다양한 배열 만들기

In [100]:
zero = np.zeros([3, 4])

In [101]:
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [102]:
one = np.ones([3, 4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [103]:
# 대각행렬
eye = np.eye(3)
print(eye) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Numpy 제공 함수

범용함수

In [104]:
arr1 = np.array([-1, -2, -3, -4])
abs_arr = np.abs(arr1) # array의 절댓값 함수

print(abs_arr)

[1 2 3 4]


In [106]:
arr2 = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr2) # array의 제곱근 함수

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [108]:
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a) # 배열의 평균값을 구해주는 함수

print(a_mean)

3.0


In [111]:
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b) # 배열의 중앙값을 구해주는 함수

print(b_median)

5.0


In [112]:
c = np.array([1, 2, 3, 4, 5])
c_std = np.std(c) # 배열의 표준편차값을 구해주는 함수

print(c_std)

1.4142135623730951


In [114]:
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d) # 배열의 분산값을 구해주는 함수

print(d_var) 

2.0


In [115]:
d = np.array([1, 2, 3, 4, 5])
d_sum = np.sum(d) # 배열의 합을 구해주는 함수

print(d_sum) # 반환값: 숫자

15


In [116]:
d_cumsum = np.cumsum(d) # 배열의 누적합계를 구해주는 함수
print(d_cumsum) # 반환값: 배열

[ 1  3  6 10 15]


In [117]:
min = np.argmin(d) # 배열 중 가장 최솟값의 인덱싱을 알려주는 함수
print(min) # 반환값: 인덱스 값

0


In [118]:
max = np.argmax(d) # 배열 중 가장 최댓값의 인덱싱을 알려주는 함수
print(max) # 반환값: 인덱스 값

4


In [119]:
a = np.array([0, 0, 0, 1])

a_true = np.any(a) # 배열 안에 하나라도 true가 있는지 확인하는 함수
print(a_true)

True


In [120]:
a_all = np.all(a) # 배열 안에 값이 모두 true여야 true로 반환하는 함수
print(a_all)

False


In [121]:
# NaN (0이 아닌 비어있다, 없다 라는 뜻. 계산은 0처럼 함)

a = np.array([1, 2, np.nan, 4])
a_nsum = np.nansum(a)

print(a_nsum)

7.0


In [123]:
a_sum = np.sum(a)
print(a_sum)

nan


In [125]:
d = np.array([1, 2, 3, 4, 5])

condition = np.where(d < 3) # 조건에 맞는 값만 출력
print(condition) # 반환값: 튜플(인덱싱)

(array([0, 1]),)


In [126]:
d = np.array([1, 2, 3, 4, 5])

condition = np.where(d < 3, d, 0) # 조건에 맞는 값은 d를 넣고 아닌 같은 0을 넣어주세요
print(condition)

[1 2 0 0 0]


### Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 원본 데이터

# 원본 데이터는 되도록이면 건들이면 안 된다.
# 원본 데이터는 오염되면 안 된다.
# 복사본을 만들어서 사용해야 됨.

In [131]:
even_a = a[a % 2 == 0]
print(even_a)
print(a) # 원본 데이터는 그대로

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast (브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해주 
- ex) 1차원, 2차원

In [132]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [133]:
d = np.array([[1], [2], [3]]) # 2차원 행렬
e = np.array([4, 5, 6]) # 1차원 벡터 

f = d + e
print(f) # d와 e의 차원이 다르지만 결과 값이 나온다
# e = np.array([[4, 5, 6]]) 으로 수정하여 연산함

[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때까지 1을 추가한다.

- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제된다.

- 두 배열의 차원 수가 같을 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.